version: '3.7'

services:
    postgresql:
        image: postgres:latest
        container_name: 'clean-architecture'
        restart: always
        ports:
            - "5555:5555"
        environment:
            - POSTGRES_PASSWORD="clean-architecture"
            - POSTGRES_USER="clean-architecture"
            - DATABASE="clean_architecture"
